model_list:
  - model_name: gemini-1.5-flash
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://nexus_ollama:11434
  - model_name: gpt-4o
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://nexus_ollama:11434
  - model_name: gpt-4
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://nexus_ollama:11434
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://nexus_ollama:11434
  - model_name: llama3.2:3b
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://nexus_ollama:11434
general_settings:
  master_key: sk-nexus-sovereign-mrf103
  drop_params: true
litellm_settings:
  drop_params: true
  set_verbose: false
  num_retries: 2
  request_timeout: 120
