apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-prime

resources:
- namespace.yaml
- secrets.yaml
- configmap.yaml
- pvc.yaml
- db.yaml
- ollama.yaml
- redis.yaml
- litellm.yaml
- cortex.yaml
- auth.yaml
- hpa.yaml
- ingress.yaml
- networkpolicy.yaml
